server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    sources:
      youtube: false # disable youtube on lavalink to use youtube-source
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    password: "youshallnotpass"
    bufferDurationMs: 225
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 3
    opusEncodingQuality: 5
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 5000
    playerUpdateInterval: 3
    useSeekGhosting: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0" # LavaSrc - extra sources like deezer, spotify, etc. https://github.com/topi314/LavaSrc
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0" # https://github.com/topi314/LavaSearch
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0" # https://github.com/DuncteBot/skybot-lavalink-plugin
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.devoxin:lavadspx-plugin:0.0.5" # https://github.com/devoxin/LavaDSPX-Plugin
      repository: "https://jitpack.io"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.3" # https://github.com/lavalink-devs/youtube-source
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0" # https://github.com/topi314/LavaLyrics
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "me.duncte123:java-lyrics-plugin:1.6.5" # https://github.com/DuncteBot/java-timed-lyrics
      repository: "https://maven.lavalink.dev/releases"
plugins:
  youtube:
    enabled: true
    oauth:
      enabled: true
      clientId: "168985442810-dnolmt66n1476l80o5gmoetq8ft38o70.apps.googleusercontent.com"
      clientSecret: "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"
      redirectUri: "http://localhost:2333/callback"
      scopes:
        - "https://www.googleapis.com/auth/youtube.readonly"
      apiKey: "AIzaSyAXPmsSMJ_i9ZjgL0vyUpQ6BsIF6c3wTA4"
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - TVHTML5EMBEDDED
      - MEDIA_CONNECT
      - IOS
    MUSIC:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: false
    WEB:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: true
    WEBEMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: false
      playback: true
    TVHTML5EMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: false
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "spsearch:%QUERY%"
      - "sprec:%QUERY%"
    sources:
      spotify: true
      youtube: false
      soundcloud: true
    spotify:
      clientId: "a8b172082c064c9a8d38314a669c0779"
      clientSecret: "1fb17b2c5ac6443b9f4b0f0fad4c4819"
      countryCode: "US"
      playlistLoadLimit: 3 # The number of pages at 100 tracks each
      albumLoadLimit: 2 # The number of pages at 50 tracks each
      localFiles: true
    youtube:
      countryCode: "US"
    dunctebot:
      ttsLanguage: "en-US"
      sources:
        getyarn: true # www.getyarn.io
        clypit: true # www.clyp.it
        tts: true # speak:Words to speak
        pornhub: true # should be self-explanatory
        reddit: true # should be self-explanatory
        ocremix: true # www.ocremix.org
        tiktok: true # tiktok.com
        mixcloud: true # mixcloud.com
        soundgasm: true # soundgasm.net
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
logging:
  file:
    max-history: 5
    max-size: 10MB
  path: ./logs/
  level:
    root: INFO
    lavalink: DEBUG
    lavalink.server.io.SocketContext: TRACE
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
    dev.lavalink.youtube: DEBUG
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5